site_name: audioio

repo_url: https://github.com/bendalab/audioio/

site_author: Benda-Lab

theme: readthedocs

markdown_extensions:
    - markdown_include.include
    
nav:
    - Home: 'index.md'
    - API reference: 'api/index.html'
