dist: xenial

language: python

matrix:
    include:
        - python: "3.6"
          os: linux
        - python: "2.7"
          os: linux

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libsndfile1
    - libsndfile1-dev
    - libffi-dev
    - libportaudio2
    - portaudio19-dev
    - osspd

before_install:
  - pip install -U pip

install:
  - pip install numpy
  - pip install scipy
  - pip install wavefile
  - pip install scikits.audiolab
  - pip install git+https://github.com/melizalab/py-ewave
  - pip install sounddevice
  - pip install nose nose-cov
  - pip install codecov
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests -vv --with-coverage --cover-package=audioio

after_success:
  - codecov
